// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_stone_collector = "CgkI2OmU4LMBEAIQCA"; // <GPGSID>
        public const string achievement_insane_jumper = "CgkI2OmU4LMBEAIQBA"; // <GPGSID>
        public const string achievement_mineral_collector = "CgkI2OmU4LMBEAIQCg"; // <GPGSID>
        public const string achievement_black_as_your_soul = "CgkI2OmU4LMBEAIQEA"; // <GPGSID>
        public const string achievement_you_need_swimming_lessons = "CgkI2OmU4LMBEAIQEQ"; // <GPGSID>
        public const string achievement_advance_medal_collector = "CgkI2OmU4LMBEAIQBg"; // <GPGSID>
        public const string achievement_normal_jumper = "CgkI2OmU4LMBEAIQAQ"; // <GPGSID>
        public const string achievement_all_the_green_you_wannabe = "CgkI2OmU4LMBEAIQDg"; // <GPGSID>
        public const string achievement_nuts_collector = "CgkI2OmU4LMBEAIQCw"; // <GPGSID>
        public const string achievement_insane_medal_collector = "CgkI2OmU4LMBEAIQBw"; // <GPGSID>
        public const string achievement_food_collector = "CgkI2OmU4LMBEAIQDA"; // <GPGSID>
        public const string achievement_noob_medal_collector = "CgkI2OmU4LMBEAIQBQ"; // <GPGSID>
        public const string achievement_boxing_bag = "CgkI2OmU4LMBEAIQEg"; // <GPGSID>
        public const string achievement_mr_bist = "CgkI2OmU4LMBEAIQEw"; // <GPGSID>
        public const string achievement_advanced_jumper = "CgkI2OmU4LMBEAIQAg"; // <GPGSID>
        public const string achievement_cows_collector = "CgkI2OmU4LMBEAIQDQ"; // <GPGSID>
        public const string achievement_fire_man = "CgkI2OmU4LMBEAIQDw"; // <GPGSID>
        public const string achievement_wood_collector = "CgkI2OmU4LMBEAIQCQ"; // <GPGSID>
        public const string achievement_noob_jumper = "CgkI2OmU4LMBEAIQAA"; // <GPGSID>
        public const string achievement_expert_jumper = "CgkI2OmU4LMBEAIQAw"; // <GPGSID>

}

